export const customizedOrderActions = {
    UPDATE_ALL_DATA: "UPDATE_ALL_DATA",
    UPDATE_BASE_DATA: "UPDATE_BASE_DATA",
    UPDATE_SCRUB_DATA: "UPDATE_SCRUB_DATA",
    UPDATE_TYPE_DATA: "UPDATE_TYPE_DATA",
    UPDATE_FRAGRANCE_DATA: "UPDATE_FRAGRANCE_DATA",
    UPDATE_ESSENTIAL_OIL_DATA: "UPDATE_ESSENTIAL_OIL_DATA",
    UPDATE_QUANTITY: "UPDATE_QUANTITY",
    CLEAR_CART_DATA: "CLEAR_CART_DATA",
}