export const userConstants = {
    USER_UPDATE_ALL_DATA: "USER_UPDATE_ALL_DATA",
    USER_CLEAR_DATA: "USER_CLEAR_DATA",
    UPDATE_CART_DATA: "UPDATE_CART_DATA",
    UPDATE_USER_ORDERS: "UPDATE_USER_ORDERS",
    UPDATE_USER_AUTHENTICATION_STATUS: "UPDATE_USER-AUTHENTICATION_STATUS",
    USER_CLEAR_REGULAR_PRODUCTS: "USER_CLEAR_REGULAR_PRODUCTS",
    USER_CLEAR_CUSTOMIZED_PRODUCTS: "USER_CLEAR_CUSTOMIZED_PRODUCTS",
}